[package]
name = "bookkeep"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "*", features = ["derive"] }
serde-tuple-vec-map = "*"
serde_yaml = "*"
time = { version = "*", features = ["serde-human-readable"] }
